apiVersion: v1
kind: BuildConfig
metadata:
  name: ola
spec:
  nodeSelector: 
    type: builder
  output:
    to:
      kind: DockerImage
      name: example-quayecosystem-quay-quay.apps.cluster-nyc-ea98.nyc-ea98.example.opentlc.com/security/ola:1-1
    pushSecret:
      name: "security-openshift-pull-secret"
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java-base-layer:release
    type: Source
  triggers: []
