apiVersion: v1
kind: BuildConfig
metadata:
  name: ola
spec:
  nodeSelector: 
    type: builder
  output:
    to:
      kind: DockerImage
      name: example-quayecosystem-quay-quay-enterprise.apps.cluster-adaf.sandbox508.opentlc.com/quay/ola:1-1
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: java-base-layer:release
    type: Docker
  triggers: []
